### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Wyrmhero42** [Uldgiw/music-script#2]
Wanted to execute

`python music.py -m 9cdb6dae-95c8-479a-892f-e762c8390cfd`

and got this after some time:

```
Traceback (most recent call last):
  File "/home/leonhard/music-script/music.py", line 15, in <module>
    songlist = brainz(args.musicbrainz)
  File "/home/leonhard/music-script/data.py", line 33, in brainz
    song.init_song(int(recording['length'])/1000)
  File "/home/leonhard/music-script/song.py", line 69, in init_song
    dur_list = [seconds(i) for i in get_list_criteria(
  File "/home/leonhard/music-script/song.py", line 69, in <listcomp>
    dur_list = [seconds(i) for i in get_list_criteria(
  File "/home/leonhard/music-script/song.py", line 17, in seconds
    dur = dur.split(":")
AttributeError: 'int' object has no attribute 'split'
```

**Comment by Uldgiw** [comment]
Thanks, the problem was that a youtube-video had a broken duration
